spring.application.name=backend
jwt.jwtSecret=Z3JlZW5iYWNrLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS0yMDI2LTAzLTI2
jwt.jwtExpirationMs=86400000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.datasource.url=jdbc:postgresql://localhost:5432/Construction
spring.datasource.username=postgres
server.port=9000
spring.datasource.password=laure
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true